name: Extrator Roadmap

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  run-extrator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Recriar credenciais.json
        run: echo '${{ secrets.CREDENCIAIS_JSON }}' > credenciais.json
        
      - name: Debug - checar variável
        run: |
          if [ -z "$ID_PASTA_ROADMAPS" ]; then
            echo "❌ Variável NÃO chegou no ambiente"
          else
            echo "✅ Variável chegou, tamanho: ${#ID_PASTA_ROADMAPS}"
          fi
        env:
          ID_PASTA_ROADMAPS: ${{ secrets.ID_PASTA_ROADMAPS }}

      - name: Rodar script
        run: python extrator_roadmap.py
        env:
          ID_PASTA_ROADMAPS: ${{ secrets.ID_PASTA_ROADMAPS }}
          ID_DESTINO: ${{ secrets.ID_DESTINO }}